### ISSUE TITLE
Error with Start

### ISSUE THREAD

**Issue by h4rk8s** [personoids/personoids-lite#1]
My Env : M1 Mac book Pro
Docker : OrbStack
When I put : `docker-compose up`,output 👇🏻
[+] Building 0.0s (0/0)
[+] Running 3/0
 ✔ Container chat-ai-plugin-clickhouse-1  Created                                                                                                                             0.0s
 ✔ Container chat-ai-plugin-chroma-1      Created                                                                                                                             0.0s
 ✔ Container chat-ai-plugin-plugin-1      Created                                                                                                                             0.0s
Attaching to chat-ai-plugin-chroma-1, chat-ai-plugin-clickhouse-1, chat-ai-plugin-plugin-1
chat-ai-plugin-clickhouse-1  | Processing configuration file '/etc/clickhouse-server/config.xml'.
chat-ai-plugin-clickhouse-1  | Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
chat-ai-plugin-clickhouse-1  | Logging trace to /var/log/clickhouse-server/clickhouse-server.log
chat-ai-plugin-clickhouse-1  | Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
chat-ai-plugin-chroma-1      | Rebuilding hnsw to ensure architecture compatibility
chat-ai-plugin-clickhouse-1  | Processing configuration file '/etc/clickhouse-server/config.xml'.
chat-ai-plugin-clickhouse-1  | Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
chat-ai-plugin-clickhouse-1  | Saved preprocessed configuration to '/var/lib/clickhouse/preprocessed_configs/config.xml'.
chat-ai-plugin-clickhouse-1  | Processing configuration file '/etc/clickhouse-server/users.xml'.
chat-ai-plugin-clickhouse-1  | Saved preprocessed configuration to '/var/lib/clickhouse/preprocessed_configs/users.xml'.
chat-ai-plugin-chroma-1      | Collecting hnswlib
chat-ai-plugin-plugin-1      |
chat-ai-plugin-plugin-1      | > personoids-chat-ai-plugin@1.0.0 start
chat-ai-plugin-plugin-1      | > node src/index.js
chat-ai-plugin-plugin-1      |
chat-ai-plugin-plugin-1      | chroma_url http://chroma:8000
chat-ai-plugin-plugin-1      | Server running at http://localhost:5004
chat-ai-plugin-plugin-1      | chroma not ready yet Error: TypeError: fetch failed
chat-ai-plugin-plugin-1      |     at ChromaClient.getOrCreateCollection (/app/node_modules/chromadb/dist/main/index.js:645:19)
chat-ai-plugin-plugin-1      |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
chat-ai-plugin-plugin-1      |     at async InMemoryDocumentStore.initialize (file:///app/src/InMemoryDocumentStore.js:12:24)
chat-ai-plugin-plugin-1      |     at async InMemoryDocumentStores.getOrCreateStore (file:///app/src/InMemoryDocumentStores.js:11:7)
chat-ai-plugin-plugin-1      |     at async InMemoryDocumentStores.initialize (file:///app/src/InMemoryDocumentStores.js:17:36)
chat-ai-plugin-plugin-1      |     at async init (file:///app/src/PersonoidLiteKernel.js:32:5)
chat-ai-plugin-chroma-1      |   Downloading hnswlib-0.7.0.tar.gz (33 kB)
chat-ai-plugin-chroma-1      |   Installing build dependencies: started
chat-ai-plugin-chroma-1      |   Installing build dependencies: finished with status 'done'
chat-ai-plugin-chroma-1      |   Getting requirements to build wheel: started
chat-ai-plugin-chroma-1      |   Getting requirements to build wheel: finished with status 'done'
chat-ai-plugin-chroma-1      |   Preparing metadata (pyproject.toml): started
chat-ai-plugin-chroma-1      |   Preparing metadata (pyproject.toml): finished with status 'done'
chat-ai-plugin-chroma-1      | Collecting numpy
chat-ai-plugin-chroma-1      |   Downloading numpy-1.24.3-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (14.0 MB)
chat-ai-plugin-plugin-1      | chroma not ready yet Error: TypeError: fetch failed
chat-ai-plugin-plugin-1      |     at ChromaClient.getOrCreateCollection (/app/node_modules/chromadb/dist/main/index.js:645:19)
chat-ai-plugin-plugin-1      |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
chat-ai-plugin-plugin-1      |     at async InMemoryDocumentStore.initialize (file:///app/src/InMemoryDocumentStore.js:12:24)
chat-ai-plugin-plugin-1      |     at async InMemoryDocumentStores.getOrCreateStore (file:///app/src/InMemoryDocumentStores.js:11:7)
chat-ai-plugin-plugin-1      |     at async InMemoryDocumentStores.initialize (file:///app/src/InMemoryDocumentStores.js:17:36)
chat-ai-plugin-plugin-1      |     at async init (file:///app/src/PersonoidLiteKernel.js:32:5)
chat-ai-plugin-chroma-1      |      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 5.2 MB/s eta 0:00:00
chat-ai-plugin-chroma-1      | Building wheels for collected packages: hnswlib
chat-ai-plugin-chroma-1      |   Building wheel for hnswlib (pyproject.toml): started
chat-ai-plugin-chroma-1      |   Building wheel for hnswlib (pyproject.toml): finished with status 'error'
chat-ai-plugin-chroma-1      |   error: subprocess-exited-with-error
chat-ai-plugin-chroma-1      |
chat-ai-plugin-chroma-1      |   × Building wheel for hnswlib (pyproject.toml) did not run successfully.
chat-ai-plugin-chroma-1      |   │ exit code: 1
chat-ai-plugin-chroma-1      |   ╰─> [55 lines of output]
chat-ai-plugin-chroma-1      |       running bdist_wheel
chat-ai-plugin-chroma-1      |       running build
chat-ai-plugin-chroma-1      |       running build_ext
chat-ai-plugin-chroma-1      |       creating tmp
chat-ai-plugin-chroma-1      |       gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.10 -c /tmp/tmp0llphgwz.cpp -o tmp/tmp0llphgwz.o -std=c++14
chat-ai-plugin-chroma-1      |       gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.10 -c /tmp/tmpeyea0c5p.cpp -o tmp/tmpeyea0c5p.o -std=c++11
chat-ai-plugin-chroma-1      |       Traceback (most recent call last):
chat-ai-plugin-chroma-1      |         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
chat-ai-plugin-chroma-1      |           main()
chat-ai-plugin-chroma-1      |         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
chat-ai-plugin-chroma-1      |           json_out['return_val'] = hook(**hook_input['kwargs'])
chat-ai-plugin-chroma-1      |         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
chat-ai-plugin-chroma-1      |           return _build_backend().build_wheel(wheel_directory, config_settings,
chat-ai-plugin-chroma-1      |         File "/tmp/pip-build-env-uwvt51tb/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 416, in build_wheel
chat-ai-plugin-chroma-1      |           return self._build_with_temp_dir(['bdist_wheel'], '.whl',
chat-ai-plugin-chroma-1      |         File "/tmp/pip-build-env-uwvt51tb/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
chat-ai-plugin-chroma-1      |           self.run_setup()
chat-ai-plugin-chroma-1      |         File "/tmp/pip-build-env-uwvt51tb/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
chat-ai-plugin-chroma-1      |           exec(code, locals())
chat-ai-plugin-chroma-1      |         File "<string>", line 116, in <module>
chat-ai-plugin-chroma-1      |         File "/tmp/pip-build-env-uwvt51tb/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
chat-ai-plugin-chroma-1      |           return distutils.core.setup(**attrs)
chat-ai-plugin-chroma-1      |         File "/tmp/pip-build-env-uwvt51tb/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
chat-ai-plugin-chroma-1      |           return run_commands(dist)
chat-ai-plugin-chroma-1      |         File "/tmp/pip-build-env-uwvt51tb/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
chat-ai-plugin-chroma-1      |           dist.run_commands()
chat-ai-plugin-chroma-1      |         File "/tmp/pip-build-env-uwvt51tb/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
chat-ai-plugin-chroma-1      |           self.run_command(cmd)
chat-ai-plugin-chroma-1      |         File "/tmp/pip-build-env-uwvt51tb/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1244, in run_command
chat-ai-plugin-chroma-1      |           super().run_command(command)
chat-ai-plugin-chroma-1      |         File "/tmp/pip-build-env-uwvt51tb/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
chat-ai-plugin-chroma-1      |           cmd_obj.run()
chat-ai-plugin-chroma-1      |         File "/tmp/pip-build-env-uwvt51tb/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 343, in run
chat-ai-plugin-chroma-1      |           self.run_command("build")
chat-ai-plugin-chroma-1      |         File "/tmp/pip-build-env-uwvt51tb/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
chat-ai-plugin-chroma-1      |           self.distribution.run_command(command)
chat-ai-plugin-chroma-1      |         File "/tmp/pip-build-env-uwvt51tb/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1244, in run_command
chat-ai-plugin-chroma-1      |           super().run_command(command)
chat-ai-plugin-chroma-1      |         File "/tmp/pip-build-env-uwvt51tb/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
chat-ai-plugin-chroma-1      |           cmd_obj.run()
chat-ai-plugin-chroma-1      |         File "/tmp/pip-build-env-uwvt51tb/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
chat-ai-plugin-chroma-1      |           self.run_command(cmd_name)
chat-ai-plugin-chroma-1      |         File "/tmp/pip-build-env-uwvt51tb/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
chat-ai-plugin-chroma-1      |           self.distribution.run_command(command)
chat-ai-plugin-chroma-1      |         File "/tmp/pip-build-env-uwvt51tb/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1244, in run_command
chat-ai-plugin-chroma-1      |           super().run_command(command)
chat-ai-plugin-chroma-1      |         File "/tmp/pip-build-env-uwvt51tb/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
chat-ai-plugin-chroma-1      |           cmd_obj.run()
chat-ai-plugin-chroma-1      |         File "/tmp/pip-build-env-uwvt51tb/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
chat-ai-plugin-chroma-1      |           _build_ext.run(self)
chat-ai-plugin-chroma-1      |         File "/tmp/pip-build-env-uwvt51tb/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
chat-ai-plugin-chroma-1      |           self.build_extensions()
chat-ai-plugin-chroma-1      |         File "<string>", line 103, in build_extensions
chat-ai-plugin-chroma-1      |         File "<string>", line 70, in cpp_flag
chat-ai-plugin-chroma-1      |       RuntimeError: Unsupported compiler -- at least C++11 support is needed!
chat-ai-plugin-chroma-1      |       [end of output]
chat-ai-plugin-chroma-1      |
chat-ai-plugin-chroma-1      |   note: This error originates from a subprocess, and is likely not a problem with pip.
chat-ai-plugin-chroma-1      |   ERROR: Failed building wheel for hnswlib
chat-ai-plugin-chroma-1      | Failed to build hnswlib
chat-ai-plugin-chroma-1      | ERROR: Could not build wheels for hnswlib, which is required to install pyproject.toml-based projects
chat-ai-plugin-chroma-1      |
chat-ai-plugin-chroma-1      | [notice] A new release of pip is available: 23.0.1 -> 23.1.2
chat-ai-plugin-chroma-1      | [notice] To update, run: pip install --upgrade pip
chat-ai-plugin-chroma-1      | 2023-05-29 05:52:28 INFO     chromadb.telemetry.posthog Anonymized telemetry enabled. See https://docs.trychroma.com/telemetry for more information.
chat-ai-plugin-chroma-1      | 2023-05-29 05:52:28 INFO     uvicorn.error   Started server process [46]
chat-ai-plugin-chroma-1      | 2023-05-29 05:52:28 INFO     uvicorn.error   Waiting for application startup.
chat-ai-plugin-chroma-1      | 2023-05-29 05:52:28 INFO     uvicorn.error   Application startup complete.
chat-ai-plugin-chroma-1      | 2023-05-29 05:52:28 INFO     uvicorn.error   Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

**Comment by noamd-legit** [comment]
I get the same error on Mac - M2

**Comment by rheaton64** [comment]
Same error on Windows 11 Pro

**Comment by tmuskal** [comment]
that chroma error is a part of the startup of the chroma's docker. but it is non-critical.
the plugin should reconnect to it once it's running (it takes a minute or two), we updated the plugin to output a bit less noise and a clear message when it is read. (please git pull and rebuild the docker)
